services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./css:/usr/share/nginx/html/css:ro
      - ./js:/usr/share/nginx/html/js
      - ./img:/usr/share/nginx/html/img:ro
    restart: unless-stopped
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON=${SUPABASE_ANON}
    command: >
      /bin/sh -c "
      sed -i 's|VITE_SUPABASE_URL|'\"$${SUPABASE_URL}\"'|g' /usr/share/nginx/html/js/config.js && 
      sed -i 's|VITE_SUPABASE_ANON|'\"$${SUPABASE_ANON}\"'|g' /usr/share/nginx/html/js/config.js && 
      nginx -g 'daemon off;'
      "